[package]
name    = "postino"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

[profile.release]
lto = true

[dependencies]
clap  = "2"
json  = "0.11"
shlex = "0.1"

threadpool = "1.0"
num_cpus   = "1.0"

mailbox = "0.2"
fs2     = "0.4"
notify  = "4.0"
