[package]
name    = "postino"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

[dependencies]
clap = "2"
json = "0.10"

threadpool = "1.0"
num_cpus   = "1.0"

mailbox = "0.1.2"
fs2     = "0.2"
notify  = "2.0"
